### ISSUE TITLE
HistoryRequestMiddleware not defined

### ISSUE THREAD

**Issue by jhotujec** [treyhunner/django-simple-history#248]
Following official guide I get this error:

`django.core.exceptions.ImproperlyConfigured: WSGI application 'optilimo.wsgi.application' could not be loaded; Error importing module: 'Module "simple_history.middleware" does not define a "HistoryRequestMiddleware" attribute/class'`

Any ideas how to fix this? Thanks!

**Comment by macro1** [comment]
I believe this is related to a change in the middleware API in Django 1.10. That should be addressed in master now. I'm going to optimistically close this, please do reopen if the changes in master don't resolve the issue you're seeing.

**Comment by GoudekettingRM** [comment]
Sorry to open up this old issue, but if I add the app like so:

```py
INSTALLED_APPS = [
    ....,
    "simple_history",
    ....
]
```
and the middleware like so:
```py
MIDDLEWARE = [
    ....,
    "simple_history.middleware.HistoryRequestMiddleware",
]
```

I get this same error once more:

```
 ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: WSGI application 'rocketfuel.wsgi.application' could not be loaded; Error importing module.
```

```
Django: 3.0.3.
DjangoSimpleHistory: 3.5.0
Python: 3.9.16
```

**Comment by ddabble** [comment]
@GoudekettingRM We don't support Django versions below 3.2 (see the supported versions in the README or in [the docs](https://django-simple-history.readthedocs.io/en/latest/)). Does the issue persist if you upgrade Django to one of the supported versions - preferably 5.0? 🙂
